#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    j=n-1
    x=arr[j]
    while j>0:
        out=""
        if x<arr[j-1]:
            arr[j]=arr[j-1]
            for i in arr:
                out+=str(i)+" "
            print(out)
        else:
            break
        j-=1
    arr[j]=x
    cout=""
    for i in arr:
        cout+=str(i)+" "
    print(cout)

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
